#! /bin/sh

# source the colors.
source "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
bspc config presel_border_color "$color1"
variety;sleep 2s & 

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width          3
bspc config window_gap            12


bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding           22
bspc config bottom_padding        22

# assign desktop to applications
bspc rule -a systemsettings desktop='^1'
bspc rule -a thunderbird desktop='^1'
bspc rule -a firefoxdeveloperedition desktop='^2' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Atom desktop='^3'
bspc rule -a Code desktop='^4'
bspc rule -a Lollypop desktop='^4'
bspc rule -a retroarch desktop='^4' follow=on
bspc rule -a VirtualBox Manager desktop='^4' follow=on
bspc rule -a VirtualBox Machine desktop='^4' follow=on

# applications rules
bspc rule -a Conky state=floating manage=off lower=on
bspc rule -a Plasma state=floating manage=off layer=normal
bspc rule -a plasmashell sticky=on layer=above state=floating
bspc rule -a albert state=floating focus=on follow=on border=off
bspc rule -a Wrapper-2.0 state=floating border=off manage=off
bspc rule -a "Whisker Menu" state=floating border=off manage=off
bspc rule -a xfce4-session floating=on fullscreen=on
bspc rule -a xfce4-panel floating=on manage=off
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a feh state=floating
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen

$HOME/.config/bspwm/autostart.sh
